"""
FastAPI inference server for RN-CodeGen.

Start the server
----------------
uvicorn inference.api:app --host 0.0.0.0 --port 8000 --reload

Endpoints
---------
POST /generate        — generate React Native code from a prompt
GET  /health          — liveness check
GET  /docs            — Swagger UI (auto-generated by FastAPI)

Example request
---------------
curl -X POST http://localhost:8000/generate \\
  -H "Content-Type: application/json" \\
  -d '{"prompt": "Create a React Native FlatList with pull-to-refresh", "num_beams": 4}'
"""

import os
import sys
import time
import logging
from contextlib import asynccontextmanager

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from inference.generate import RNCodeGenerator
from training.config import cfg

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger(__name__)


# ── Model lifecycle ───────────────────────────────────────────────────────────

generator: RNCodeGenerator | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load model on startup, release on shutdown."""
    global generator
    model_dir = os.environ.get("MODEL_DIR", cfg.output_dir)
    logger.info(f"Loading model from: {model_dir}")
    generator = RNCodeGenerator(model_dir)
    logger.info("Model ready.")
    yield
    generator = None
    logger.info("Model unloaded.")


# ── App ───────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="RN-CodeGen API",
    description=(
        "Generate React Native component code from natural-language descriptions "
        "using a fine-tuned CodeT5 model."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # tighten this in production
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Schemas ───────────────────────────────────────────────────────────────────

class GenerateRequest(BaseModel):
    prompt: str = Field(
        ...,
        min_length=5,
        max_length=256,
        description="Natural-language description of the React Native component",
        examples=["Create a React Native FlatList with pull-to-refresh"],
    )
    num_beams: int = Field(default=4, ge=1, le=10, description="Beam-search width")
    max_new_tokens: int = Field(default=512, ge=32, le=1024)
    num_return_sequences: int = Field(default=1, ge=1, le=4)


class GenerateResponse(BaseModel):
    prompt: str
    code: str | list[str]
    latency_ms: float


class HealthResponse(BaseModel):
    status: str
    model_loaded: bool


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/health", response_model=HealthResponse, tags=["Utility"])
def health():
    return {"status": "ok", "model_loaded": generator is not None}


@app.post("/generate", response_model=GenerateResponse, tags=["CodeGen"])
def generate(request: GenerateRequest):
    if generator is None:
        raise HTTPException(status_code=503, detail="Model not loaded yet")

    t0 = time.perf_counter()
    code = generator.generate(
        prompt=request.prompt,
        num_beams=request.num_beams,
        max_new_tokens=request.max_new_tokens,
        num_return_sequences=request.num_return_sequences,
    )
    latency_ms = (time.perf_counter() - t0) * 1000

    logger.info(f"Generated in {latency_ms:.0f} ms | prompt: {request.prompt[:60]}")
    return GenerateResponse(prompt=request.prompt, code=code, latency_ms=round(latency_ms, 1))
